
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: projetao_development
  username: postgres
  password: example
  host: localhost

test:
  <<: *default
  database: projetao_test

production:
  <<: *default
  database: projetao_production
  username: projetao
  password: <%= ENV["PROJETAO_DATABASE_PASSWORD"] %>
